### PR TITLE
Update naw.sh

### PR DESCRIPTION
**Pull request by Walkman100**
Fix unknown command response.

All this does is if `--help test` is passed, instead of returning:
`Unknown command "--help"` - which is a valid command - it will now return:
`Unknown command "--help test"` - which isn't a valid command.

---
This change is [Reviewable](https://reviewable.io/reviews/nawproject/naw/5)

### CODE REVIEW

**Comment by deavmi** [comment]
@Walkman100 No need to do this stuff

**Comment by deavmi** [comment]
@deavmi The way I want to.

**Comment by deavmi** [comment]
@deavmi I will fix all of it anyway

**Comment by deavmi** [comment]
I said I would be fixing the whole args system.

On 18 April 2016 11:30:20 PM SAST, "░̟▒̱̈́͑ͩ▓̰̣̹̝ͪ̀̔̈͠█͒ͨ��│̺̫͚͛̐̎́͊【W̳̬̽́̆̌ȁ̧̩̥͇̄͒l͇̆̎̎̐ͥk͚̙͚͇̈́̈ͣ̍̽̓m̜̤̰͚̼̟a̝̘͎̍̎n̛̝̤͗̅̈̇͗ͨ̾ͅ】͚̝͚̤̗̮ͩ̉̏͢│̧̲͚̺͎̪̾ͮ█̈́��̞̱̙̭͘▓̪̙̝̜̹̬▒̶̄░̵̭̫̤��" <notifications@github.com> wrote:
>Fix unknown command response.
>
>All this does is if `--help test` is passed, instead of returning:
>`Unknown command "--help"` - which is a valid command - it will now
>return:
>`Unknown command "--help test"` - which isn't a valid command.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/nawproject/naw/pull/5
>
>-- Commit Summary --
>
>  * Update naw.sh
>
>-- File Changes --
>
>    M naw.sh (2)
>
>-- Patch Links --
>
>https://github.com/nawproject/naw/pull/5.patch
>https://github.com/nawproject/naw/pull/5.diff
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nawproject/naw/pull/5

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Walkman100** [comment]
So why isn't #4 merged? just close this if you don't want it, it was meant to be a temporary fix until you could fix it properly.

**Comment by deavmi** [comment]
Closed then. @Walkman100

**Pull request closed without merging**
