### PR TITLE
Updates (Fixes #3)

### LINKED ISSUE #3: Syntax error.
@Walkman100 There is a syntax error that my eyes cannot find, pls find it and fix it. Dogecoin will be paid.

### PR DESCRIPTION
**Pull request by Walkman100**
- `naw.sh`:
  - Fix spelling error, ~~make unknown command text show the full unknown command.~~
  - Fixed syntax error (#3)
- `aboutpages.sh`:
  - Fix my name and link

---
This change is [Reviewable](https://reviewable.io/reviews/nawproject/naw/4)

### CODE REVIEW

**Comment by deavmi** [comment]
@Walkman100 Will merge soon

**Comment by deavmi** [comment]
@Walkman100 Thanks

**Comment by deavmi** [comment]
I will merge as soon as this is removed "make unknown command text show the full unknown command."

**Comment by deavmi** [comment]
All I want is:

* The name fix
* The spelling fix
* Syntax fix

I will improve `init` by myself.

@Walkman100

**Comment by Walkman100** [comment]
I'll separate them then.

**Comment by deavmi** [comment]
The PRs? Thanks then.

On 18 April 2016 11:23:55 PM SAST, "░̟▒̱̈́͑ͩ▓̰̣̹̝ͪ̀̔̈͠█͒ͨ��│̺̫͚͛̐̎́͊【W̳̬̽́̆̌ȁ̧̩̥͇̄͒l͇̆̎̎̐ͥk͚̙͚͇̈́̈ͣ̍̽̓m̜̤̰͚̼̟a̝̘͎̍̎n̛̝̤͗̅̈̇͗ͨ̾ͅ】͚̝͚̤̗̮ͩ̉̏͢│̧̲͚̺͎̪̾ͮ█̈́��̞̱̙̭͘▓̪̙̝̜̹̬▒̶̄░̵̭̫̤��" <notifications@github.com> wrote:
>I'll separate them then.
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/nawproject/naw/pull/4#issuecomment-211588061

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Walkman100** [comment]
Can this one be merged?
>I will merge as soon as this is removed "make unknown command text show the full unknown command."

that was removed yesterday...

**Comment by deavmi** [comment]
@Walkman100 I haven't been on GH for a full day. If I have time tomorrow then I will merge.

**Comment by Walkman100** [comment]
Then don't say `I will merge as soon as this is removed`

**Comment by deavmi** [comment]
@Walkman100 Omit (As soon as)

**Comment by deavmi** [comment]
Merged. @Walkman100

**Pull request merged**
